### ISSUE TITLE
Rodapé com fundo e letras brancas

### ISSUE THREAD

**Issue by t3nsini** [clusterdesign/nightmode-extension#3]
Qlik Sense Server. June 2019.

Quando adicionado rodapé no objeto ele aparece com letras e fundo branco, de modo que não seja possível ler seu conteúdo.

![fundo_night](https://user-images.githubusercontent.com/60895308/74177939-73dd5580-4c19-11ea-9726-f9e14302c3f4.jpeg)

**Comment by clusterdesign** [comment]
Corrigido!
